spring:
  security:
    saml2:
      relyingparty:
        registration:
          #okta123:
          azure:
            assertingparty:
              #metadata-uri: https://dev-44683278.okta.com/app/exk6zrznadLtjnq4C5d7/sso/saml/metadata
              metadata-uri: https://login.microsoftonline.com/c3da75cd-0276-4e14-a2ab-12128bba114c/federationmetadata/2007-06/federationmetadata.xml?appid=5617aabe-6115-4fe9-b1db-ebd49be1855e